### PR TITLE
Add integration tests

### PR DESCRIPTION
**Pull request by ondrowan**
This is just a draft, so you can check how tests look like. It relates to #5.

* It requires you manually start Dgraph Docker containers, but there's no documentation for it so far.
* Dockerized Dgraph uses non-standard ports to prevent clashes with any other local Dgraph instance.
* There are no tests for secure connection. I'll need to create images with certificates and figure out how to painlessly set it up for local development.
* Tests need to be run with `cargo test -- --test-threads=1` since Dgraph likes to abort transactions if it modifies the same data at the same time. This is not documented yet.
* Query tests use just `uid` queries since those always resolve.
* `it_discards_a_transaction` fails for some reason and I'm not sure why. `discard` complains that `Transaction has been aborted. Please retry.`, but I don't see a reason why. I'll look into it later.

### CODE REVIEW

**Comment by Swoorup** [comment]
Apologies for the delay. I have been busy with other stuffs. I am happy with the changes. This is a pretty good start. Happy to merge in as is, and we can integrate it with CI later

**Comment by ondrowan** [comment]
@Swoorup As you can see, I was swamped with work lately as well 😀 I've comitted everything from my checklist, but I cannot figure out why that one test fails. Could it be some bug? I've compared it with implementation and tests from [dgraph-io/dgraph-js](https://github.com/dgraph-io/dgraph-js/) and the code _seems_ to be the same. Could you check it once you have some time to spare?

**Comment by ondrowan** [comment]
@Swoorup since I'd like to work on other things I temporarily commented the failing test out and will figure out what's happening over there later. It'd be still cool if you looked at it as well.

**Comment by Swoorup** [comment]
Happy with the changes so far 👍

**Pull request merged**
