### PR TITLE
Update to latest API and add support for best-effort queries.

### PR DESCRIPTION
**Pull request by martinmr**
- Run cargo fmt.
- Update api.proto file and recompile.
- Add support for best-effort queries.

### CODE REVIEW

**Comment by martinmr** [comment]
Hi. I work at Dgraph and I've been wanting to learn rust for a bit. I saw that you have a fairly complete client for rust already so I opened this PR. The biggest change is adding support for best-effort queries.

**Comment by Swoorup** [comment]
Apologies for the delay. The changes look good, do you want to fix up the indentation in the changes? 

I use rustfmt to autoformat the code.

**Comment by martinmr** [comment]
I used a tool (cargo fmt, I think) to format the changes. Not sure why the output of rustfmt and cargo fmt differ. I'll try to update my rust toolchain and try again with rustfmt.

**Comment by martinmr** [comment]
I updated rust and `cargo fmt` and `rustfmt` produce the same output in my machine.

**Comment by Swoorup** [comment]
Ah nvm, it looks like I have mixed spaces and tabs in the repo. Not a big deal. Will merge it for now.

**Comment by ondrowan** [comment]
@martinmr Is there any reason why best effort queries are set through a method instead of parameter in `new_readonly_txn`? This type of query can be run only as read only anyway and it seems like it opens a needless vector for misconfiguration if it's done through a method. I checked Go Dgraph repo and they do it the same way for some reason 😶

**Comment by martinmr** [comment]
Yeah, I also thought it was a bit weird but I didn't design that particular API so I went for consistency with the other clients.

**Pull request merged**
