### PR TITLE
Add support for Dgraph 1.1

### PR DESCRIPTION
**Pull request by ondrowan**
This patch adds support for Dgraph 1.1 through a feature flag. By
default, installed crate supports Dgraph 1.0 out of the box. If user
needs 1.1 support, they have to disable default feature flags and
provide "dgraph-1-1" one. This is most likely just a temporary solution
while Dgraph 1.0 is supported and this library catches up with its
official counterparts feature-wise.

### CODE REVIEW

**Comment by ondrowan** [comment]
This is not finished yet. I still need to set up Travis, polish tests and document new features. I'll potentially also implement version of `query` that uses new `do_request` API.

I decided to go the harder, but IMO more user friendly way. This PR gives users support for both Dgraph 1.0 and 1.1, depending on what they choose via a feature flag. I'm still not sure if using default feature flag or explicit one is a better idea in case of Dgraph 1.0.

If someone could test this, I'd be grateful.

@martinmr @Pepeye Since you two showed interest in #10, I'm tagging you just FYI.

**Comment by Swoorup** [comment]
I will have a bit more look at this weekend. 

On this occasion, I prefer keeping only the latest stable rather than keeping both versions at any given time and thus providing a migration guide. However does Dgraph have plans to keep supporting 1.0?

**Comment by ondrowan** [comment]
I'd prefer that as well, but I saw that there are still releases for Dgraph 1.0 as well. But maybe @martinmr would have an answer for this.

**Comment by martinmr** [comment]
We might release new versions of 1.0 but they will only contain bugfixes. So the current release of the rust client should work.

**Comment by martinmr** [comment]
We might release new versions of 1.0 but they will only contain bugfixes. So the current release of the rust client should work.

**Comment by d0nutptr** [comment]
Any idea on when this might get merged in? I'm currently unable to use this library due to a lack of 1.1 support :(

**Review by Swoorup — APPROVED** [review]
Changes look good to me. Apologies for the delay. At some point I think we do have to EOL pre 1.0 support. The CI config probably has to be modified to stop the CI complaining.

**Comment by ondrowan** [comment]
@d0nutptr I'll try to fix everything there's left and merge the PR this weekend.

**Pull request merged**
